# Generated by Django 4.2 on 2024-02-29 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="admins",
            field=models.ManyToManyField(
                related_name="admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="members",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
